{% set name = "pyrost" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e295b6f4f6e9aaed6ba60df813f85584ac476216373bba7ae86473b72d4d01d

build:
  number: 0
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - libblas
    - python
    - pip
    - cython
    - gsl
    - fftw
    - h5py
    - numpy
    - scipy
    - tqdm
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - h5py
    - tqdm

test:
  imports:
    - pyrost
  requires:
    - pytest
    - pip
  source_files:
    - tests/test_pyrost.py
    - pytest.ini
  commands:
    - pytest tests -m standalone
    - pip check

about:
  home: https://github.com/simply-nicky/pyrost
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Robust Speckle Tracking library'
  description: |
    Python Robust Speckle Tracking (pyrost) is a library for wavefront metrology
    and sample imaging based on ptychographic speckle tracking algorithm.
  doc_url: https://robust-speckle-tracking.readthedocs.io/

extra:
  recipe-maintainers:
    - simply-nicky
